import type { Tool } from './types'

export const toolIconByName: Record<string, string> = {
  Linux: '/svg/tools/linux.svg',
  Nginx: '/svg/tools/nginx.svg',
  Docker: '/svg/tools/docker.svg',
  Kubernetes: '/svg/tools/kubernetes.svg',
  k8s: '/svg/tools/kubernetes.svg',
  Helm: '/svg/tools/helm.svg',
  Terraform: '/svg/tools/terraform.svg',
  Cloudflare: '/svg/tools/cloudflare.svg',
  WAF: '/svg/tools/waf.svg',
  UFW: '/svg/tools/ufw.svg',
  iptables: '/svg/tools/iptables.svg',
  Fail2Ban: '/svg/tools/fail2ban.svg',
  Cilium: '/svg/tools/cilium.svg',
  SonarQube: '/svg/tools/sonarqube.svg',
  Trivy: '/svg/tools/trivy.svg',
  Vault: '/svg/tools/vault.svg',
  Grafana: '/svg/tools/grafana.svg',
  Prometheus: '/svg/tools/prometheus.svg',
  CEPH: '/svg/tools/ceph.svg',
  S3: '/svg/tools/s3.svg',
  RAID: '/svg/tools/raid.svg',
  Restic: '/svg/tools/backup.svg',
  Backups: '/svg/tools/backup.svg',
  Snapshots: '/svg/tools/snapshot.svg',
  PostgreSQL: '/svg/tools/postgresql.svg',
  MySQL: '/svg/tools/mysql.svg',
  Redis: '/svg/tools/redis.svg',
  AWS: '/svg/tools/aws.svg',
  'Google Cloud': '/svg/tools/google-cloud.svg',
  'Let’s Encrypt': '/svg/tools/ssl.svg',
  TLS: '/svg/tools/ssl.svg',
  'Zero Trust': '/svg/tools/zero-trust.svg',
  systemd: '/svg/tools/systemd.svg',
  journalctl: '/svg/tools/logs.svg',
  k6: '/svg/tools/load-test.svg',
  wrk: '/svg/tools/load-test.svg',
  ab: '/svg/tools/load-test.svg',
}

export const heroTools: Tool[] = [
  { name: 'Linux', icon: toolIconByName.Linux, tone: 'yellow' },
  { name: 'Nginx', icon: toolIconByName.Nginx, tone: 'green' },
  { name: 'Docker', icon: toolIconByName.Docker, tone: 'blue' },
  { name: 'Kubernetes', icon: toolIconByName.Kubernetes, tone: 'cyan' },
  { name: 'Terraform', icon: toolIconByName.Terraform, tone: 'green' },
  { name: 'Cloudflare', icon: toolIconByName.Cloudflare, tone: 'yellow' },
  { name: 'WAF', icon: toolIconByName.WAF, tone: 'pink' },
  { name: 'CEPH', icon: toolIconByName.CEPH, tone: 'cyan' },
]

export const securityTools: Tool[] = [
  { name: 'UFW', icon: toolIconByName.UFW, tone: 'green' },
  { name: 'iptables', icon: toolIconByName.iptables, tone: 'cyan' },
  { name: 'Fail2Ban', icon: toolIconByName.Fail2Ban, tone: 'yellow' },
  { name: 'Cilium', icon: toolIconByName.Cilium, tone: 'blue' },
  { name: 'SonarQube', icon: toolIconByName.SonarQube, tone: 'pink' },
  { name: 'Trivy', icon: toolIconByName.Trivy, tone: 'green' },
  { name: 'Vault', icon: toolIconByName.Vault, tone: 'yellow' },
  { name: 'Grafana', icon: toolIconByName.Grafana, tone: 'cyan' },
  { name: 'CEPH', icon: toolIconByName.CEPH, tone: 'blue' },
  { name: 'Prometheus', icon: toolIconByName.Prometheus, tone: 'pink' },
]

export const toolMarqueeItems = [
  'Linux',
  'Nginx',
  'Docker',
  'Kubernetes',
  'Helm',
  'Terraform',
  'CEPH',
  'Cloudflare',
  'WAF',
  'Fail2Ban',
  'UFW',
  'iptables',
  'Cilium',
  'Grafana',
  'Prometheus',
  'SonarQube',
  'Trivy',
  'Vault',
  'PostgreSQL',
  'MySQL',
  'Redis',
  'AWS',
  'Google Cloud',
]

export function getToolIcon(toolName: string) {
  return toolIconByName[toolName] ?? ''
}
